import { StyleSheet } from 'react-native';

/** Stampza brand tokens from product screenshots */
export const colors = {
  coral: '#FF5A5F',
  coralDark: '#E8484D',
  coralSoft: '#FF8A8E',
  pink: '#FFF0F1',
  pinkDeep: '#FFE0E3',
  bg: '#FFF7F7',
  ink: '#1C1C1E',
  muted: '#8E8E93',
  white: '#FFFFFF',
  border: 'rgba(28,28,30,0.08)',
  success: '#34C759',
  warning: '#FF9F0A',
  shadow: 'rgba(255,90,95,0.18)',
};

export const radii = {
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  pill: 999,
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  pad: { padding: 20, paddingBottom: 48 },
  brand: {
    color: colors.coral,
    fontSize: 34,
    fontWeight: '900',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  h1: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: 6,
    letterSpacing: -0.4,
  },
  h2: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: 8,
    marginTop: 16,
  },
  muted: { color: colors.muted, marginBottom: 8, fontSize: 14, lineHeight: 20 },
  sectionLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginTop: 8,
  },
  input: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
    fontSize: 16,
    color: colors.ink,
  },
  inputFocused: { borderColor: colors.coral },
  btn: {
    backgroundColor: colors.coral,
    borderRadius: radii.pill,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginVertical: 6,
    shadowColor: colors.coral,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  btnOutline: {
    backgroundColor: colors.white,
    borderRadius: radii.pill,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginVertical: 6,
    borderWidth: 1.5,
    borderColor: colors.coral,
  },
  btnGhost: {
    backgroundColor: colors.pink,
    borderRadius: radii.pill,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginVertical: 6,
  },
  btnText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  btnTextOutline: { color: colors.coral, fontWeight: '700', fontSize: 16 },
  error: { color: '#B91C1C', marginBottom: 8, fontWeight: '600' },
  hint: { color: colors.muted, fontSize: 12, marginTop: 12, lineHeight: 18 },
  card: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardTitle: { fontWeight: '800', fontSize: 16, color: colors.ink },
  kpi: { fontSize: 24, fontWeight: '800', color: colors.ink, marginTop: 4 },
  kpiLabel: { fontSize: 12, color: colors.muted, fontWeight: '600' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 4 },
  badge: {
    marginTop: 8,
    backgroundColor: colors.pink,
    color: colors.coral,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.pill,
    fontWeight: '700',
    alignSelf: 'flex-start',
    fontSize: 13,
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chipOn: {
    backgroundColor: colors.coral,
    borderColor: colors.coral,
  },
  chipText: { color: colors.ink, fontWeight: '600', fontSize: 13 },
  chipTextOn: { color: colors.white, fontWeight: '700', fontSize: 13 },
  scanHero: {
    backgroundColor: colors.coral,
    borderRadius: radii.xl,
    padding: 18,
    marginBottom: 16,
  },
  scanFrame: {
    height: 280,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: '#1a1a1a',
    marginTop: 12,
  },
  heroCard: {
    backgroundColor: colors.pink,
    borderRadius: radii.xl,
    padding: 20,
    marginBottom: 16,
  },
  iconTile: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.pink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginLeft: 52,
  },
});

export { colors as theme };
