/* eslint-disable */
/** Auto-generated by apps/api/scripts/build-media-library.mjs — do not edit by hand. */
export type GeneratedMediaLibraryItem = {
  id: string;
  categoryGroup: string;
  categorySlug?: string;
  label: string;
  path: string;
};

export const MEDIA_LIBRARY_GENERATED: GeneratedMediaLibraryItem[] = [
  {
    "id": "food-beverage-activity-square",
    "categoryGroup": "food-beverage",
    "label": "Activity Square",
    "path": "/library/food-beverage/activity-square.svg"
  },
  {
    "id": "food-beverage-alert-octagon",
    "categoryGroup": "food-beverage",
    "label": "Alert Octagon",
    "path": "/library/food-beverage/alert-octagon.svg"
  },
  {
    "id": "food-beverage-amphora",
    "categoryGroup": "food-beverage",
    "label": "Amphora",
    "path": "/library/food-beverage/amphora.svg"
  },
  {
    "id": "food-beverage-apple",
    "categoryGroup": "food-beverage",
    "label": "Apple",
    "path": "/library/food-beverage/apple.svg"
  },
  {
    "id": "food-beverage-asterisk",
    "categoryGroup": "food-beverage",
    "label": "Asterisk",
    "path": "/library/food-beverage/asterisk.svg"
  },
  {
    "id": "food-beverage-badge-euro",
    "categoryGroup": "food-beverage",
    "label": "Badge Euro",
    "path": "/library/food-beverage/badge-euro.svg"
  },
  {
    "id": "food-beverage-badge-percent",
    "categoryGroup": "food-beverage",
    "label": "Badge Percent",
    "path": "/library/food-beverage/badge-percent.svg"
  },
  {
    "id": "food-beverage-banana",
    "categoryGroup": "food-beverage",
    "label": "Banana",
    "path": "/library/food-beverage/banana.svg"
  },
  {
    "id": "food-beverage-banknote-x",
    "categoryGroup": "food-beverage",
    "label": "Banknote X",
    "path": "/library/food-beverage/banknote-x.svg"
  },
  {
    "id": "food-beverage-battery-medium",
    "categoryGroup": "food-beverage",
    "label": "Battery Medium",
    "path": "/library/food-beverage/battery-medium.svg"
  },
  {
    "id": "food-beverage-bean",
    "categoryGroup": "food-beverage",
    "label": "Bean",
    "path": "/library/food-beverage/bean.svg"
  },
  {
    "id": "food-beverage-beef",
    "categoryGroup": "food-beverage",
    "label": "Beef",
    "path": "/library/food-beverage/beef.svg"
  },
  {
    "id": "food-beverage-beer",
    "categoryGroup": "food-beverage",
    "label": "Beer",
    "path": "/library/food-beverage/beer.svg",
    "categorySlug": "bar-pub-loyalty"
  },
  {
    "id": "food-beverage-biceps-flexed",
    "categoryGroup": "food-beverage",
    "label": "Biceps Flexed",
    "path": "/library/food-beverage/biceps-flexed.svg"
  },
  {
    "id": "food-beverage-blender",
    "categoryGroup": "food-beverage",
    "label": "Blender",
    "path": "/library/food-beverage/blender.svg"
  },
  {
    "id": "food-beverage-bomb",
    "categoryGroup": "food-beverage",
    "label": "Bomb",
    "path": "/library/food-beverage/bomb.svg"
  },
  {
    "id": "food-beverage-book-open-check",
    "categoryGroup": "food-beverage",
    "label": "Book Open Check",
    "path": "/library/food-beverage/book-open-check.svg"
  },
  {
    "id": "food-beverage-bookmark-off",
    "categoryGroup": "food-beverage",
    "label": "Bookmark Off",
    "path": "/library/food-beverage/bookmark-off.svg"
  },
  {
    "id": "food-beverage-brick-wall-shield",
    "categoryGroup": "food-beverage",
    "label": "Brick Wall Shield",
    "path": "/library/food-beverage/brick-wall-shield.svg"
  },
  {
    "id": "food-beverage-cake",
    "categoryGroup": "food-beverage",
    "label": "Cake",
    "path": "/library/food-beverage/cake.svg",
    "categorySlug": "bakery-stamp-card"
  },
  {
    "id": "food-beverage-cake-slice",
    "categoryGroup": "food-beverage",
    "label": "Cake Slice",
    "path": "/library/food-beverage/cake-slice.svg",
    "categorySlug": "bakery-stamp-card"
  },
  {
    "id": "food-beverage-calendar-clock",
    "categoryGroup": "food-beverage",
    "label": "Calendar Clock",
    "path": "/library/food-beverage/calendar-clock.svg"
  },
  {
    "id": "food-beverage-candy",
    "categoryGroup": "food-beverage",
    "label": "Candy",
    "path": "/library/food-beverage/candy.svg"
  },
  {
    "id": "food-beverage-candy-cane",
    "categoryGroup": "food-beverage",
    "label": "Candy Cane",
    "path": "/library/food-beverage/candy-cane.svg"
  },
  {
    "id": "food-beverage-carrot",
    "categoryGroup": "food-beverage",
    "label": "Carrot",
    "path": "/library/food-beverage/carrot.svg"
  },
  {
    "id": "food-beverage-chef-hat",
    "categoryGroup": "food-beverage",
    "label": "Chef Hat",
    "path": "/library/food-beverage/chef-hat.svg",
    "categorySlug": "restaurant-rewards"
  },
  {
    "id": "food-beverage-cherry",
    "categoryGroup": "food-beverage",
    "label": "Cherry",
    "path": "/library/food-beverage/cherry.svg"
  },
  {
    "id": "food-beverage-citrus",
    "categoryGroup": "food-beverage",
    "label": "Citrus",
    "path": "/library/food-beverage/citrus.svg"
  },
  {
    "id": "food-beverage-clock",
    "categoryGroup": "food-beverage",
    "label": "Clock",
    "path": "/library/food-beverage/clock.svg"
  },
  {
    "id": "food-beverage-coffee",
    "categoryGroup": "food-beverage",
    "label": "Coffee",
    "path": "/library/food-beverage/coffee.svg",
    "categorySlug": "coffee-stamp-card"
  },
  {
    "id": "food-beverage-cookie",
    "categoryGroup": "food-beverage",
    "label": "Cookie",
    "path": "/library/food-beverage/cookie.svg",
    "categorySlug": "bakery-stamp-card"
  },
  {
    "id": "food-beverage-cooking-pot",
    "categoryGroup": "food-beverage",
    "label": "Cooking Pot",
    "path": "/library/food-beverage/cooking-pot.svg"
  },
  {
    "id": "food-beverage-croissant",
    "categoryGroup": "food-beverage",
    "label": "Croissant",
    "path": "/library/food-beverage/croissant.svg",
    "categorySlug": "bakery-stamp-card"
  },
  {
    "id": "food-beverage-cup-soda",
    "categoryGroup": "food-beverage",
    "label": "Cup Soda",
    "path": "/library/food-beverage/cup-soda.svg",
    "categorySlug": "bubble-tea-rewards"
  },
  {
    "id": "food-beverage-donut",
    "categoryGroup": "food-beverage",
    "label": "Donut",
    "path": "/library/food-beverage/donut.svg",
    "categorySlug": "bakery-stamp-card"
  },
  {
    "id": "food-beverage-drumstick",
    "categoryGroup": "food-beverage",
    "label": "Drumstick",
    "path": "/library/food-beverage/drumstick.svg"
  },
  {
    "id": "food-beverage-egg",
    "categoryGroup": "food-beverage",
    "label": "Egg",
    "path": "/library/food-beverage/egg.svg"
  },
  {
    "id": "food-beverage-egg-fried",
    "categoryGroup": "food-beverage",
    "label": "Egg Fried",
    "path": "/library/food-beverage/egg-fried.svg"
  },
  {
    "id": "food-beverage-fish",
    "categoryGroup": "food-beverage",
    "label": "Fish",
    "path": "/library/food-beverage/fish.svg"
  },
  {
    "id": "food-beverage-flame",
    "categoryGroup": "food-beverage",
    "label": "Flame",
    "path": "/library/food-beverage/flame.svg"
  },
  {
    "id": "food-beverage-glass-water",
    "categoryGroup": "food-beverage",
    "label": "Glass Water",
    "path": "/library/food-beverage/glass-water.svg",
    "categorySlug": "juice-bar-loyalty"
  },
  {
    "id": "food-beverage-grape",
    "categoryGroup": "food-beverage",
    "label": "Grape",
    "path": "/library/food-beverage/grape.svg"
  },
  {
    "id": "food-beverage-hamburger",
    "categoryGroup": "food-beverage",
    "label": "Hamburger",
    "path": "/library/food-beverage/hamburger.svg",
    "categorySlug": "fast-food-loyalty"
  },
  {
    "id": "food-beverage-heart",
    "categoryGroup": "food-beverage",
    "label": "Heart",
    "path": "/library/food-beverage/heart.svg"
  },
  {
    "id": "food-beverage-hop",
    "categoryGroup": "food-beverage",
    "label": "Hop",
    "path": "/library/food-beverage/hop.svg"
  },
  {
    "id": "food-beverage-ice-cream-bowl",
    "categoryGroup": "food-beverage",
    "label": "Ice Cream Bowl",
    "path": "/library/food-beverage/ice-cream-bowl.svg",
    "categorySlug": "ice-cream-rewards"
  },
  {
    "id": "food-beverage-ice-cream-cone",
    "categoryGroup": "food-beverage",
    "label": "Ice Cream Cone",
    "path": "/library/food-beverage/ice-cream-cone.svg",
    "categorySlug": "ice-cream-rewards"
  },
  {
    "id": "food-beverage-leaf",
    "categoryGroup": "food-beverage",
    "label": "Leaf",
    "path": "/library/food-beverage/leaf.svg"
  },
  {
    "id": "food-beverage-map-pin",
    "categoryGroup": "food-beverage",
    "label": "Map Pin",
    "path": "/library/food-beverage/map-pin.svg"
  },
  {
    "id": "food-beverage-martini",
    "categoryGroup": "food-beverage",
    "label": "Martini",
    "path": "/library/food-beverage/martini.svg",
    "categorySlug": "bar-pub-loyalty"
  },
  {
    "id": "food-beverage-microwave",
    "categoryGroup": "food-beverage",
    "label": "Microwave",
    "path": "/library/food-beverage/microwave.svg"
  },
  {
    "id": "food-beverage-milk",
    "categoryGroup": "food-beverage",
    "label": "Milk",
    "path": "/library/food-beverage/milk.svg"
  },
  {
    "id": "food-beverage-milk-off",
    "categoryGroup": "food-beverage",
    "label": "Milk Off",
    "path": "/library/food-beverage/milk-off.svg"
  },
  {
    "id": "food-beverage-moon",
    "categoryGroup": "food-beverage",
    "label": "Moon",
    "path": "/library/food-beverage/moon.svg"
  },
  {
    "id": "food-beverage-nut",
    "categoryGroup": "food-beverage",
    "label": "Nut",
    "path": "/library/food-beverage/nut.svg"
  },
  {
    "id": "food-beverage-pizza",
    "categoryGroup": "food-beverage",
    "label": "Pizza",
    "path": "/library/food-beverage/pizza.svg",
    "categorySlug": "pizza-stamp-card"
  },
  {
    "id": "food-beverage-popcorn",
    "categoryGroup": "food-beverage",
    "label": "Popcorn",
    "path": "/library/food-beverage/popcorn.svg",
    "categorySlug": "cinema"
  },
  {
    "id": "food-beverage-receipt",
    "categoryGroup": "food-beverage",
    "label": "Receipt",
    "path": "/library/food-beverage/receipt.svg"
  },
  {
    "id": "food-beverage-refrigerator",
    "categoryGroup": "food-beverage",
    "label": "Refrigerator",
    "path": "/library/food-beverage/refrigerator.svg"
  },
  {
    "id": "food-beverage-salad",
    "categoryGroup": "food-beverage",
    "label": "Salad",
    "path": "/library/food-beverage/salad.svg",
    "categorySlug": "juice-bar-loyalty"
  },
  {
    "id": "food-beverage-sandwich",
    "categoryGroup": "food-beverage",
    "label": "Sandwich",
    "path": "/library/food-beverage/sandwich.svg"
  },
  {
    "id": "food-beverage-smile",
    "categoryGroup": "food-beverage",
    "label": "Smile",
    "path": "/library/food-beverage/smile.svg"
  },
  {
    "id": "food-beverage-soup",
    "categoryGroup": "food-beverage",
    "label": "Soup",
    "path": "/library/food-beverage/soup.svg"
  },
  {
    "id": "food-beverage-star",
    "categoryGroup": "food-beverage",
    "label": "Star",
    "path": "/library/food-beverage/star.svg"
  },
  {
    "id": "food-beverage-store",
    "categoryGroup": "food-beverage",
    "label": "Store",
    "path": "/library/food-beverage/store.svg",
    "categorySlug": "online-store"
  },
  {
    "id": "food-beverage-sun",
    "categoryGroup": "food-beverage",
    "label": "Sun",
    "path": "/library/food-beverage/sun.svg"
  },
  {
    "id": "food-beverage-thermometer",
    "categoryGroup": "food-beverage",
    "label": "Thermometer",
    "path": "/library/food-beverage/thermometer.svg"
  },
  {
    "id": "food-beverage-utensils",
    "categoryGroup": "food-beverage",
    "label": "Utensils",
    "path": "/library/food-beverage/utensils.svg",
    "categorySlug": "catering-service"
  },
  {
    "id": "food-beverage-utensils-crossed",
    "categoryGroup": "food-beverage",
    "label": "Utensils Crossed",
    "path": "/library/food-beverage/utensils-crossed.svg",
    "categorySlug": "restaurant-rewards"
  },
  {
    "id": "food-beverage-vegan",
    "categoryGroup": "food-beverage",
    "label": "Vegan",
    "path": "/library/food-beverage/vegan.svg"
  },
  {
    "id": "food-beverage-wheat",
    "categoryGroup": "food-beverage",
    "label": "Wheat",
    "path": "/library/food-beverage/wheat.svg"
  },
  {
    "id": "food-beverage-wine",
    "categoryGroup": "food-beverage",
    "label": "Wine",
    "path": "/library/food-beverage/wine.svg",
    "categorySlug": "bar-pub-loyalty"
  },
  {
    "id": "retail-ad",
    "categoryGroup": "retail",
    "label": "AD",
    "path": "/library/retail/ad.svg"
  },
  {
    "id": "retail-alert-triangle",
    "categoryGroup": "retail",
    "label": "Alert Triangle",
    "path": "/library/retail/alert-triangle.svg"
  },
  {
    "id": "retail-asterisk-square",
    "categoryGroup": "retail",
    "label": "Asterisk Square",
    "path": "/library/retail/asterisk-square.svg"
  },
  {
    "id": "retail-backpack",
    "categoryGroup": "retail",
    "label": "Backpack",
    "path": "/library/retail/backpack.svg"
  },
  {
    "id": "retail-badge-dollar-sign",
    "categoryGroup": "retail",
    "label": "Badge Dollar Sign",
    "path": "/library/retail/badge-dollar-sign.svg"
  },
  {
    "id": "retail-badge-help",
    "categoryGroup": "retail",
    "label": "Badge Help",
    "path": "/library/retail/badge-help.svg"
  },
  {
    "id": "retail-banknote",
    "categoryGroup": "retail",
    "label": "Banknote",
    "path": "/library/retail/banknote.svg"
  },
  {
    "id": "retail-bar-chart",
    "categoryGroup": "retail",
    "label": "Bar Chart",
    "path": "/library/retail/bar-chart.svg"
  },
  {
    "id": "retail-barcode",
    "categoryGroup": "retail",
    "label": "Barcode",
    "path": "/library/retail/barcode.svg"
  },
  {
    "id": "retail-battery-plus",
    "categoryGroup": "retail",
    "label": "Battery Plus",
    "path": "/library/retail/battery-plus.svg"
  },
  {
    "id": "retail-binoculars",
    "categoryGroup": "retail",
    "label": "Binoculars",
    "path": "/library/retail/binoculars.svg"
  },
  {
    "id": "retail-bone-fracture",
    "categoryGroup": "retail",
    "label": "Bone Fracture",
    "path": "/library/retail/bone-fracture.svg"
  },
  {
    "id": "retail-book",
    "categoryGroup": "retail",
    "label": "Book",
    "path": "/library/retail/book.svg",
    "categorySlug": "bookstore"
  },
  {
    "id": "retail-book-open",
    "categoryGroup": "retail",
    "label": "Book Open",
    "path": "/library/retail/book-open.svg",
    "categorySlug": "bookstore"
  },
  {
    "id": "retail-book-open-text",
    "categoryGroup": "retail",
    "label": "Book Open Text",
    "path": "/library/retail/book-open-text.svg"
  },
  {
    "id": "retail-bookmark-plus",
    "categoryGroup": "retail",
    "label": "Bookmark Plus",
    "path": "/library/retail/bookmark-plus.svg"
  },
  {
    "id": "retail-briefcase",
    "categoryGroup": "retail",
    "label": "Briefcase",
    "path": "/library/retail/briefcase.svg"
  },
  {
    "id": "retail-briefcase-conveyor-belt",
    "categoryGroup": "retail",
    "label": "Briefcase Conveyor Belt",
    "path": "/library/retail/briefcase-conveyor-belt.svg"
  },
  {
    "id": "retail-brush",
    "categoryGroup": "retail",
    "label": "Brush",
    "path": "/library/retail/brush.svg"
  },
  {
    "id": "retail-calendar-cog",
    "categoryGroup": "retail",
    "label": "Calendar Cog",
    "path": "/library/retail/calendar-cog.svg"
  },
  {
    "id": "retail-camera",
    "categoryGroup": "retail",
    "label": "Camera",
    "path": "/library/retail/camera.svg",
    "categorySlug": "photography-studio"
  },
  {
    "id": "retail-coins",
    "categoryGroup": "retail",
    "label": "Coins",
    "path": "/library/retail/coins.svg"
  },
  {
    "id": "retail-credit-card",
    "categoryGroup": "retail",
    "label": "Credit Card",
    "path": "/library/retail/credit-card.svg"
  },
  {
    "id": "retail-crown",
    "categoryGroup": "retail",
    "label": "Crown",
    "path": "/library/retail/crown.svg"
  },
  {
    "id": "retail-diamond",
    "categoryGroup": "retail",
    "label": "Diamond",
    "path": "/library/retail/diamond.svg",
    "categorySlug": "jewelry-store"
  },
  {
    "id": "retail-eraser",
    "categoryGroup": "retail",
    "label": "Eraser",
    "path": "/library/retail/eraser.svg"
  },
  {
    "id": "retail-footprints",
    "categoryGroup": "retail",
    "label": "Footprints",
    "path": "/library/retail/footprints.svg"
  },
  {
    "id": "retail-gem",
    "categoryGroup": "retail",
    "label": "Gem",
    "path": "/library/retail/gem.svg",
    "categorySlug": "jewelry-store"
  },
  {
    "id": "retail-gift",
    "categoryGroup": "retail",
    "label": "Gift",
    "path": "/library/retail/gift.svg",
    "categorySlug": "gift-shop"
  },
  {
    "id": "retail-glasses",
    "categoryGroup": "retail",
    "label": "Glasses",
    "path": "/library/retail/glasses.svg",
    "categorySlug": "clothing-store"
  },
  {
    "id": "retail-headphones",
    "categoryGroup": "retail",
    "label": "Headphones",
    "path": "/library/retail/headphones.svg",
    "categorySlug": "electronics-store"
  },
  {
    "id": "retail-highlighter",
    "categoryGroup": "retail",
    "label": "Highlighter",
    "path": "/library/retail/highlighter.svg"
  },
  {
    "id": "retail-laptop",
    "categoryGroup": "retail",
    "label": "Laptop",
    "path": "/library/retail/laptop.svg",
    "categorySlug": "electronics-store"
  },
  {
    "id": "retail-library",
    "categoryGroup": "retail",
    "label": "Library",
    "path": "/library/retail/library.svg",
    "categorySlug": "bookstore"
  },
  {
    "id": "retail-monitor",
    "categoryGroup": "retail",
    "label": "Monitor",
    "path": "/library/retail/monitor.svg"
  },
  {
    "id": "retail-package",
    "categoryGroup": "retail",
    "label": "Package",
    "path": "/library/retail/package.svg",
    "categorySlug": "subscription-box"
  },
  {
    "id": "retail-package-check",
    "categoryGroup": "retail",
    "label": "Package Check",
    "path": "/library/retail/package-check.svg"
  },
  {
    "id": "retail-package-open",
    "categoryGroup": "retail",
    "label": "Package Open",
    "path": "/library/retail/package-open.svg"
  },
  {
    "id": "retail-package-plus",
    "categoryGroup": "retail",
    "label": "Package Plus",
    "path": "/library/retail/package-plus.svg"
  },
  {
    "id": "retail-palette",
    "categoryGroup": "retail",
    "label": "Palette",
    "path": "/library/retail/palette.svg"
  },
  {
    "id": "retail-pen",
    "categoryGroup": "retail",
    "label": "Pen",
    "path": "/library/retail/pen.svg"
  },
  {
    "id": "retail-pencil",
    "categoryGroup": "retail",
    "label": "Pencil",
    "path": "/library/retail/pencil.svg"
  },
  {
    "id": "retail-percent",
    "categoryGroup": "retail",
    "label": "Percent",
    "path": "/library/retail/percent.svg"
  },
  {
    "id": "retail-printer",
    "categoryGroup": "retail",
    "label": "Printer",
    "path": "/library/retail/printer.svg",
    "categorySlug": "printing-service"
  },
  {
    "id": "retail-puzzle",
    "categoryGroup": "retail",
    "label": "Puzzle",
    "path": "/library/retail/puzzle.svg"
  },
  {
    "id": "retail-qr-code",
    "categoryGroup": "retail",
    "label": "QR Code",
    "path": "/library/retail/qr-code.svg"
  },
  {
    "id": "retail-ruler",
    "categoryGroup": "retail",
    "label": "Ruler",
    "path": "/library/retail/ruler.svg"
  },
  {
    "id": "retail-scan-barcode",
    "categoryGroup": "retail",
    "label": "Scan Barcode",
    "path": "/library/retail/scan-barcode.svg"
  },
  {
    "id": "retail-scissors",
    "categoryGroup": "retail",
    "label": "Scissors",
    "path": "/library/retail/scissors.svg",
    "categorySlug": "hair-salon"
  },
  {
    "id": "retail-shirt",
    "categoryGroup": "retail",
    "label": "Shirt",
    "path": "/library/retail/shirt.svg",
    "categorySlug": "clothing-store"
  },
  {
    "id": "retail-shopping-bag",
    "categoryGroup": "retail",
    "label": "Shopping Bag",
    "path": "/library/retail/shopping-bag.svg"
  },
  {
    "id": "retail-shopping-basket",
    "categoryGroup": "retail",
    "label": "Shopping Basket",
    "path": "/library/retail/shopping-basket.svg",
    "categorySlug": "supermarket"
  },
  {
    "id": "retail-shopping-cart",
    "categoryGroup": "retail",
    "label": "Shopping Cart",
    "path": "/library/retail/shopping-cart.svg",
    "categorySlug": "supermarket"
  },
  {
    "id": "retail-smartphone",
    "categoryGroup": "retail",
    "label": "Smartphone",
    "path": "/library/retail/smartphone.svg",
    "categorySlug": "electronics-store"
  },
  {
    "id": "retail-speaker",
    "categoryGroup": "retail",
    "label": "Speaker",
    "path": "/library/retail/speaker.svg"
  },
  {
    "id": "retail-stamp",
    "categoryGroup": "retail",
    "label": "Stamp",
    "path": "/library/retail/stamp.svg"
  },
  {
    "id": "retail-tablet",
    "categoryGroup": "retail",
    "label": "Tablet",
    "path": "/library/retail/tablet.svg"
  },
  {
    "id": "retail-tag",
    "categoryGroup": "retail",
    "label": "Tag",
    "path": "/library/retail/tag.svg"
  },
  {
    "id": "retail-tags",
    "categoryGroup": "retail",
    "label": "Tags",
    "path": "/library/retail/tags.svg"
  },
  {
    "id": "retail-ticket",
    "categoryGroup": "retail",
    "label": "Ticket",
    "path": "/library/retail/ticket.svg"
  },
  {
    "id": "retail-ticket-percent",
    "categoryGroup": "retail",
    "label": "Ticket Percent",
    "path": "/library/retail/ticket-percent.svg"
  },
  {
    "id": "retail-toy-brick",
    "categoryGroup": "retail",
    "label": "Toy Brick",
    "path": "/library/retail/toy-brick.svg"
  },
  {
    "id": "retail-wallet",
    "categoryGroup": "retail",
    "label": "Wallet",
    "path": "/library/retail/wallet.svg"
  },
  {
    "id": "retail-watch",
    "categoryGroup": "retail",
    "label": "Watch",
    "path": "/library/retail/watch.svg",
    "categorySlug": "jewelry-store"
  },
  {
    "id": "health-beauty-airplay",
    "categoryGroup": "health-beauty",
    "label": "Airplay",
    "path": "/library/health-beauty/airplay.svg"
  },
  {
    "id": "health-beauty-ampersand",
    "categoryGroup": "health-beauty",
    "label": "Ampersand",
    "path": "/library/health-beauty/ampersand.svg"
  },
  {
    "id": "health-beauty-anvil",
    "categoryGroup": "health-beauty",
    "label": "Anvil",
    "path": "/library/health-beauty/anvil.svg"
  },
  {
    "id": "health-beauty-astroid",
    "categoryGroup": "health-beauty",
    "label": "Astroid",
    "path": "/library/health-beauty/astroid.svg"
  },
  {
    "id": "health-beauty-badge-indian-rupee",
    "categoryGroup": "health-beauty",
    "label": "Badge Indian Rupee",
    "path": "/library/health-beauty/badge-indian-rupee.svg"
  },
  {
    "id": "health-beauty-bar-chart-2",
    "categoryGroup": "health-beauty",
    "label": "Bar Chart 2",
    "path": "/library/health-beauty/bar-chart-2.svg"
  },
  {
    "id": "health-beauty-bath",
    "categoryGroup": "health-beauty",
    "label": "Bath",
    "path": "/library/health-beauty/bath.svg",
    "categorySlug": "spa-wellness"
  },
  {
    "id": "health-beauty-battery-warning",
    "categoryGroup": "health-beauty",
    "label": "Battery Warning",
    "path": "/library/health-beauty/battery-warning.svg"
  },
  {
    "id": "health-beauty-biohazard",
    "categoryGroup": "health-beauty",
    "label": "Biohazard",
    "path": "/library/health-beauty/biohazard.svg"
  },
  {
    "id": "health-beauty-book-a",
    "categoryGroup": "health-beauty",
    "label": "Book A",
    "path": "/library/health-beauty/book-a.svg"
  },
  {
    "id": "health-beauty-book-plus",
    "categoryGroup": "health-beauty",
    "label": "Book Plus",
    "path": "/library/health-beauty/book-plus.svg"
  },
  {
    "id": "health-beauty-bookmark-x",
    "categoryGroup": "health-beauty",
    "label": "Bookmark X",
    "path": "/library/health-beauty/bookmark-x.svg"
  },
  {
    "id": "health-beauty-briefcase-medical",
    "categoryGroup": "health-beauty",
    "label": "Briefcase Medical",
    "path": "/library/health-beauty/briefcase-medical.svg"
  },
  {
    "id": "health-beauty-calendar-days",
    "categoryGroup": "health-beauty",
    "label": "Calendar Days",
    "path": "/library/health-beauty/calendar-days.svg"
  },
  {
    "id": "health-beauty-droplet",
    "categoryGroup": "health-beauty",
    "label": "Droplet",
    "path": "/library/health-beauty/droplet.svg"
  },
  {
    "id": "health-beauty-droplets",
    "categoryGroup": "health-beauty",
    "label": "Droplets",
    "path": "/library/health-beauty/droplets.svg"
  },
  {
    "id": "health-beauty-eye",
    "categoryGroup": "health-beauty",
    "label": "Eye",
    "path": "/library/health-beauty/eye.svg",
    "categorySlug": "eye-clinic"
  },
  {
    "id": "health-beauty-eye-off",
    "categoryGroup": "health-beauty",
    "label": "Eye Off",
    "path": "/library/health-beauty/eye-off.svg"
  },
  {
    "id": "health-beauty-flask-conical",
    "categoryGroup": "health-beauty",
    "label": "Flask Conical",
    "path": "/library/health-beauty/flask-conical.svg"
  },
  {
    "id": "health-beauty-flower",
    "categoryGroup": "health-beauty",
    "label": "Flower",
    "path": "/library/health-beauty/flower.svg",
    "categorySlug": "spa-wellness"
  },
  {
    "id": "health-beauty-flower-2",
    "categoryGroup": "health-beauty",
    "label": "Flower 2",
    "path": "/library/health-beauty/flower-2.svg",
    "categorySlug": "spa-wellness"
  },
  {
    "id": "health-beauty-hand",
    "categoryGroup": "health-beauty",
    "label": "Hand",
    "path": "/library/health-beauty/hand.svg"
  },
  {
    "id": "health-beauty-hand-heart",
    "categoryGroup": "health-beauty",
    "label": "Hand Heart",
    "path": "/library/health-beauty/hand-heart.svg"
  },
  {
    "id": "health-beauty-heart-handshake",
    "categoryGroup": "health-beauty",
    "label": "Heart Handshake",
    "path": "/library/health-beauty/heart-handshake.svg"
  },
  {
    "id": "health-beauty-paint-bucket",
    "categoryGroup": "health-beauty",
    "label": "Paint Bucket",
    "path": "/library/health-beauty/paint-bucket.svg"
  },
  {
    "id": "health-beauty-paintbrush",
    "categoryGroup": "health-beauty",
    "label": "Paintbrush",
    "path": "/library/health-beauty/paintbrush.svg"
  },
  {
    "id": "health-beauty-pipette",
    "categoryGroup": "health-beauty",
    "label": "Pipette",
    "path": "/library/health-beauty/pipette.svg"
  },
  {
    "id": "health-beauty-rose",
    "categoryGroup": "health-beauty",
    "label": "Rose",
    "path": "/library/health-beauty/rose.svg"
  },
  {
    "id": "health-beauty-scan-face",
    "categoryGroup": "health-beauty",
    "label": "Scan Face",
    "path": "/library/health-beauty/scan-face.svg"
  },
  {
    "id": "health-beauty-shower-head",
    "categoryGroup": "health-beauty",
    "label": "Shower Head",
    "path": "/library/health-beauty/shower-head.svg"
  },
  {
    "id": "health-beauty-smile-plus",
    "categoryGroup": "health-beauty",
    "label": "Smile Plus",
    "path": "/library/health-beauty/smile-plus.svg"
  },
  {
    "id": "health-beauty-soap-dispenser-droplet",
    "categoryGroup": "health-beauty",
    "label": "Soap Dispenser Droplet",
    "path": "/library/health-beauty/soap-dispenser-droplet.svg"
  },
  {
    "id": "health-beauty-sparkle",
    "categoryGroup": "health-beauty",
    "label": "Sparkle",
    "path": "/library/health-beauty/sparkle.svg"
  },
  {
    "id": "health-beauty-sparkles",
    "categoryGroup": "health-beauty",
    "label": "Sparkles",
    "path": "/library/health-beauty/sparkles.svg",
    "categorySlug": "beauty-salon"
  },
  {
    "id": "health-beauty-spray-can",
    "categoryGroup": "health-beauty",
    "label": "Spray Can",
    "path": "/library/health-beauty/spray-can.svg"
  },
  {
    "id": "health-beauty-user",
    "categoryGroup": "health-beauty",
    "label": "User",
    "path": "/library/health-beauty/user.svg"
  },
  {
    "id": "health-beauty-user-round",
    "categoryGroup": "health-beauty",
    "label": "User Round",
    "path": "/library/health-beauty/user-round.svg"
  },
  {
    "id": "health-beauty-users",
    "categoryGroup": "health-beauty",
    "label": "Users",
    "path": "/library/health-beauty/users.svg"
  },
  {
    "id": "health-beauty-wand",
    "categoryGroup": "health-beauty",
    "label": "Wand",
    "path": "/library/health-beauty/wand.svg"
  },
  {
    "id": "health-beauty-wand-sparkles",
    "categoryGroup": "health-beauty",
    "label": "Wand Sparkles",
    "path": "/library/health-beauty/wand-sparkles.svg"
  },
  {
    "id": "health-beauty-wind",
    "categoryGroup": "health-beauty",
    "label": "Wind",
    "path": "/library/health-beauty/wind.svg"
  },
  {
    "id": "fitness-accessibility",
    "categoryGroup": "fitness",
    "label": "Accessibility",
    "path": "/library/fitness/accessibility.svg"
  },
  {
    "id": "fitness-activity",
    "categoryGroup": "fitness",
    "label": "Activity",
    "path": "/library/fitness/activity.svg"
  },
  {
    "id": "fitness-alarm-check",
    "categoryGroup": "fitness",
    "label": "Alarm Check",
    "path": "/library/fitness/alarm-check.svg"
  },
  {
    "id": "fitness-ampersands",
    "categoryGroup": "fitness",
    "label": "Ampersands",
    "path": "/library/fitness/ampersands.svg"
  },
  {
    "id": "fitness-at-sign",
    "categoryGroup": "fitness",
    "label": "AT Sign",
    "path": "/library/fitness/at-sign.svg"
  },
  {
    "id": "fitness-award",
    "categoryGroup": "fitness",
    "label": "Award",
    "path": "/library/fitness/award.svg"
  },
  {
    "id": "fitness-badge-info",
    "categoryGroup": "fitness",
    "label": "Badge Info",
    "path": "/library/fitness/badge-info.svg"
  },
  {
    "id": "fitness-bar-chart-3",
    "categoryGroup": "fitness",
    "label": "Bar Chart 3",
    "path": "/library/fitness/bar-chart-3.svg"
  },
  {
    "id": "fitness-beaker",
    "categoryGroup": "fitness",
    "label": "Beaker",
    "path": "/library/fitness/beaker.svg"
  },
  {
    "id": "fitness-bike",
    "categoryGroup": "fitness",
    "label": "Bike",
    "path": "/library/fitness/bike.svg",
    "categorySlug": "gym-membership"
  },
  {
    "id": "fitness-birdhouse",
    "categoryGroup": "fitness",
    "label": "Birdhouse",
    "path": "/library/fitness/birdhouse.svg"
  },
  {
    "id": "fitness-bone",
    "categoryGroup": "fitness",
    "label": "Bone",
    "path": "/library/fitness/bone.svg",
    "categorySlug": "pet-shop"
  },
  {
    "id": "fitness-book-alert",
    "categoryGroup": "fitness",
    "label": "Book Alert",
    "path": "/library/fitness/book-alert.svg"
  },
  {
    "id": "fitness-book-search",
    "categoryGroup": "fitness",
    "label": "Book Search",
    "path": "/library/fitness/book-search.svg"
  },
  {
    "id": "fitness-boom-box",
    "categoryGroup": "fitness",
    "label": "Boom Box",
    "path": "/library/fitness/boom-box.svg"
  },
  {
    "id": "fitness-brain",
    "categoryGroup": "fitness",
    "label": "Brain",
    "path": "/library/fitness/brain.svg"
  },
  {
    "id": "fitness-bring-to-front",
    "categoryGroup": "fitness",
    "label": "Bring TO Front",
    "path": "/library/fitness/bring-to-front.svg"
  },
  {
    "id": "fitness-cloud-sun",
    "categoryGroup": "fitness",
    "label": "Cloud Sun",
    "path": "/library/fitness/cloud-sun.svg"
  },
  {
    "id": "fitness-dumbbell",
    "categoryGroup": "fitness",
    "label": "Dumbbell",
    "path": "/library/fitness/dumbbell.svg",
    "categorySlug": "gym-membership"
  },
  {
    "id": "fitness-flag",
    "categoryGroup": "fitness",
    "label": "Flag",
    "path": "/library/fitness/flag.svg"
  },
  {
    "id": "fitness-heart-pulse",
    "categoryGroup": "fitness",
    "label": "Heart Pulse",
    "path": "/library/fitness/heart-pulse.svg"
  },
  {
    "id": "fitness-medal",
    "categoryGroup": "fitness",
    "label": "Medal",
    "path": "/library/fitness/medal.svg"
  },
  {
    "id": "fitness-mountain",
    "categoryGroup": "fitness",
    "label": "Mountain",
    "path": "/library/fitness/mountain.svg"
  },
  {
    "id": "fitness-mountain-snow",
    "categoryGroup": "fitness",
    "label": "Mountain Snow",
    "path": "/library/fitness/mountain-snow.svg"
  },
  {
    "id": "fitness-move",
    "categoryGroup": "fitness",
    "label": "Move",
    "path": "/library/fitness/move.svg"
  },
  {
    "id": "fitness-move-diagonal",
    "categoryGroup": "fitness",
    "label": "Move Diagonal",
    "path": "/library/fitness/move-diagonal.svg"
  },
  {
    "id": "fitness-person-standing",
    "categoryGroup": "fitness",
    "label": "Person Standing",
    "path": "/library/fitness/person-standing.svg"
  },
  {
    "id": "fitness-scale",
    "categoryGroup": "fitness",
    "label": "Scale",
    "path": "/library/fitness/scale.svg"
  },
  {
    "id": "fitness-stretch-horizontal",
    "categoryGroup": "fitness",
    "label": "Stretch Horizontal",
    "path": "/library/fitness/stretch-horizontal.svg"
  },
  {
    "id": "fitness-stretch-vertical",
    "categoryGroup": "fitness",
    "label": "Stretch Vertical",
    "path": "/library/fitness/stretch-vertical.svg"
  },
  {
    "id": "fitness-sunrise",
    "categoryGroup": "fitness",
    "label": "Sunrise",
    "path": "/library/fitness/sunrise.svg"
  },
  {
    "id": "fitness-sunset",
    "categoryGroup": "fitness",
    "label": "Sunset",
    "path": "/library/fitness/sunset.svg"
  },
  {
    "id": "fitness-target",
    "categoryGroup": "fitness",
    "label": "Target",
    "path": "/library/fitness/target.svg"
  },
  {
    "id": "fitness-timer",
    "categoryGroup": "fitness",
    "label": "Timer",
    "path": "/library/fitness/timer.svg"
  },
  {
    "id": "fitness-timer-reset",
    "categoryGroup": "fitness",
    "label": "Timer Reset",
    "path": "/library/fitness/timer-reset.svg"
  },
  {
    "id": "fitness-trophy",
    "categoryGroup": "fitness",
    "label": "Trophy",
    "path": "/library/fitness/trophy.svg"
  },
  {
    "id": "fitness-waves",
    "categoryGroup": "fitness",
    "label": "Waves",
    "path": "/library/fitness/waves.svg",
    "categorySlug": "swimming-pool"
  },
  {
    "id": "fitness-zap",
    "categoryGroup": "fitness",
    "label": "Zap",
    "path": "/library/fitness/zap.svg"
  },
  {
    "id": "automotive-alarm-clock",
    "categoryGroup": "automotive",
    "label": "Alarm Clock",
    "path": "/library/automotive/alarm-clock.svg"
  },
  {
    "id": "automotive-angry",
    "categoryGroup": "automotive",
    "label": "Angry",
    "path": "/library/automotive/angry.svg"
  },
  {
    "id": "automotive-audio-lines",
    "categoryGroup": "automotive",
    "label": "Audio Lines",
    "path": "/library/automotive/audio-lines.svg"
  },
  {
    "id": "automotive-badge-japanese-yen",
    "categoryGroup": "automotive",
    "label": "Badge Japanese Yen",
    "path": "/library/automotive/badge-japanese-yen.svg"
  },
  {
    "id": "automotive-bar-chart-4",
    "categoryGroup": "automotive",
    "label": "Bar Chart 4",
    "path": "/library/automotive/bar-chart-4.svg"
  },
  {
    "id": "automotive-bean-off",
    "categoryGroup": "automotive",
    "label": "Bean Off",
    "path": "/library/automotive/bean-off.svg"
  },
  {
    "id": "automotive-bitcoin",
    "categoryGroup": "automotive",
    "label": "Bitcoin",
    "path": "/library/automotive/bitcoin.svg"
  },
  {
    "id": "automotive-book-audio",
    "categoryGroup": "automotive",
    "label": "Book Audio",
    "path": "/library/automotive/book-audio.svg"
  },
  {
    "id": "automotive-book-template",
    "categoryGroup": "automotive",
    "label": "Book Template",
    "path": "/library/automotive/book-template.svg"
  },
  {
    "id": "automotive-bot-message-square",
    "categoryGroup": "automotive",
    "label": "Bot Message Square",
    "path": "/library/automotive/bot-message-square.svg"
  },
  {
    "id": "automotive-broccoli",
    "categoryGroup": "automotive",
    "label": "Broccoli",
    "path": "/library/automotive/broccoli.svg"
  },
  {
    "id": "automotive-bus",
    "categoryGroup": "automotive",
    "label": "Bus",
    "path": "/library/automotive/bus.svg"
  },
  {
    "id": "automotive-bus-front",
    "categoryGroup": "automotive",
    "label": "Bus Front",
    "path": "/library/automotive/bus-front.svg"
  },
  {
    "id": "automotive-car",
    "categoryGroup": "automotive",
    "label": "Car",
    "path": "/library/automotive/car.svg",
    "categorySlug": "car-wash"
  },
  {
    "id": "automotive-car-front",
    "categoryGroup": "automotive",
    "label": "Car Front",
    "path": "/library/automotive/car-front.svg",
    "categorySlug": "auto-service-center"
  },
  {
    "id": "automotive-car-taxi-front",
    "categoryGroup": "automotive",
    "label": "Car Taxi Front",
    "path": "/library/automotive/car-taxi-front.svg"
  },
  {
    "id": "automotive-circle-gauge",
    "categoryGroup": "automotive",
    "label": "Circle Gauge",
    "path": "/library/automotive/circle-gauge.svg"
  },
  {
    "id": "automotive-cog",
    "categoryGroup": "automotive",
    "label": "Cog",
    "path": "/library/automotive/cog.svg"
  },
  {
    "id": "automotive-compass",
    "categoryGroup": "automotive",
    "label": "Compass",
    "path": "/library/automotive/compass.svg"
  },
  {
    "id": "automotive-construction",
    "categoryGroup": "automotive",
    "label": "Construction",
    "path": "/library/automotive/construction.svg"
  },
  {
    "id": "automotive-fuel",
    "categoryGroup": "automotive",
    "label": "Fuel",
    "path": "/library/automotive/fuel.svg",
    "categorySlug": "fuel-station"
  },
  {
    "id": "automotive-gauge",
    "categoryGroup": "automotive",
    "label": "Gauge",
    "path": "/library/automotive/gauge.svg"
  },
  {
    "id": "automotive-hammer",
    "categoryGroup": "automotive",
    "label": "Hammer",
    "path": "/library/automotive/hammer.svg"
  },
  {
    "id": "automotive-key",
    "categoryGroup": "automotive",
    "label": "Key",
    "path": "/library/automotive/key.svg"
  },
  {
    "id": "automotive-key-round",
    "categoryGroup": "automotive",
    "label": "Key Round",
    "path": "/library/automotive/key-round.svg"
  },
  {
    "id": "automotive-key-square",
    "categoryGroup": "automotive",
    "label": "Key Square",
    "path": "/library/automotive/key-square.svg"
  },
  {
    "id": "automotive-lock",
    "categoryGroup": "automotive",
    "label": "Lock",
    "path": "/library/automotive/lock.svg"
  },
  {
    "id": "automotive-map",
    "categoryGroup": "automotive",
    "label": "Map",
    "path": "/library/automotive/map.svg"
  },
  {
    "id": "automotive-map-pinned",
    "categoryGroup": "automotive",
    "label": "Map Pinned",
    "path": "/library/automotive/map-pinned.svg"
  },
  {
    "id": "automotive-milestone",
    "categoryGroup": "automotive",
    "label": "Milestone",
    "path": "/library/automotive/milestone.svg"
  },
  {
    "id": "automotive-navigation",
    "categoryGroup": "automotive",
    "label": "Navigation",
    "path": "/library/automotive/navigation.svg"
  },
  {
    "id": "automotive-parking-meter",
    "categoryGroup": "automotive",
    "label": "Parking Meter",
    "path": "/library/automotive/parking-meter.svg"
  },
  {
    "id": "automotive-route",
    "categoryGroup": "automotive",
    "label": "Route",
    "path": "/library/automotive/route.svg"
  },
  {
    "id": "automotive-settings",
    "categoryGroup": "automotive",
    "label": "Settings",
    "path": "/library/automotive/settings.svg"
  },
  {
    "id": "automotive-settings-2",
    "categoryGroup": "automotive",
    "label": "Settings 2",
    "path": "/library/automotive/settings-2.svg"
  },
  {
    "id": "automotive-traffic-cone",
    "categoryGroup": "automotive",
    "label": "Traffic Cone",
    "path": "/library/automotive/traffic-cone.svg"
  },
  {
    "id": "automotive-truck",
    "categoryGroup": "automotive",
    "label": "Truck",
    "path": "/library/automotive/truck.svg",
    "categorySlug": "online-store"
  },
  {
    "id": "automotive-unlock",
    "categoryGroup": "automotive",
    "label": "Unlock",
    "path": "/library/automotive/unlock.svg"
  },
  {
    "id": "automotive-van",
    "categoryGroup": "automotive",
    "label": "Van",
    "path": "/library/automotive/van.svg"
  },
  {
    "id": "automotive-wrench",
    "categoryGroup": "automotive",
    "label": "Wrench",
    "path": "/library/automotive/wrench.svg",
    "categorySlug": "auto-service-center"
  },
  {
    "id": "professional-services-alarm-clock-check",
    "categoryGroup": "professional-services",
    "label": "Alarm Clock Check",
    "path": "/library/professional-services/alarm-clock-check.svg"
  },
  {
    "id": "professional-services-annoyed",
    "categoryGroup": "professional-services",
    "label": "Annoyed",
    "path": "/library/professional-services/annoyed.svg"
  },
  {
    "id": "professional-services-aperture",
    "categoryGroup": "professional-services",
    "label": "Aperture",
    "path": "/library/professional-services/aperture.svg"
  },
  {
    "id": "professional-services-audio-lines-x",
    "categoryGroup": "professional-services",
    "label": "Audio Lines X",
    "path": "/library/professional-services/audio-lines-x.svg"
  },
  {
    "id": "professional-services-badge-check",
    "categoryGroup": "professional-services",
    "label": "Badge Check",
    "path": "/library/professional-services/badge-check.svg"
  },
  {
    "id": "professional-services-badge-minus",
    "categoryGroup": "professional-services",
    "label": "Badge Minus",
    "path": "/library/professional-services/badge-minus.svg"
  },
  {
    "id": "professional-services-bar-chart-big",
    "categoryGroup": "professional-services",
    "label": "Bar Chart Big",
    "path": "/library/professional-services/bar-chart-big.svg"
  },
  {
    "id": "professional-services-beef-off",
    "categoryGroup": "professional-services",
    "label": "Beef Off",
    "path": "/library/professional-services/beef-off.svg"
  },
  {
    "id": "professional-services-blend",
    "categoryGroup": "professional-services",
    "label": "Blend",
    "path": "/library/professional-services/blend.svg"
  },
  {
    "id": "professional-services-book-check",
    "categoryGroup": "professional-services",
    "label": "Book Check",
    "path": "/library/professional-services/book-check.svg"
  },
  {
    "id": "professional-services-book-text",
    "categoryGroup": "professional-services",
    "label": "Book Text",
    "path": "/library/professional-services/book-text.svg"
  },
  {
    "id": "professional-services-bot-off",
    "categoryGroup": "professional-services",
    "label": "Bot Off",
    "path": "/library/professional-services/bot-off.svg"
  },
  {
    "id": "professional-services-briefcase-business",
    "categoryGroup": "professional-services",
    "label": "Briefcase Business",
    "path": "/library/professional-services/briefcase-business.svg"
  },
  {
    "id": "professional-services-broom",
    "categoryGroup": "professional-services",
    "label": "Broom",
    "path": "/library/professional-services/broom.svg"
  },
  {
    "id": "professional-services-building",
    "categoryGroup": "professional-services",
    "label": "Building",
    "path": "/library/professional-services/building.svg"
  },
  {
    "id": "professional-services-building-2",
    "categoryGroup": "professional-services",
    "label": "Building 2",
    "path": "/library/professional-services/building-2.svg"
  },
  {
    "id": "professional-services-clapperboard",
    "categoryGroup": "professional-services",
    "label": "Clapperboard",
    "path": "/library/professional-services/clapperboard.svg",
    "categorySlug": "cinema"
  },
  {
    "id": "professional-services-clipboard",
    "categoryGroup": "professional-services",
    "label": "Clipboard",
    "path": "/library/professional-services/clipboard.svg"
  },
  {
    "id": "professional-services-clipboard-check",
    "categoryGroup": "professional-services",
    "label": "Clipboard Check",
    "path": "/library/professional-services/clipboard-check.svg"
  },
  {
    "id": "professional-services-contact",
    "categoryGroup": "professional-services",
    "label": "Contact",
    "path": "/library/professional-services/contact.svg"
  },
  {
    "id": "professional-services-drafting-compass",
    "categoryGroup": "professional-services",
    "label": "Drafting Compass",
    "path": "/library/professional-services/drafting-compass.svg"
  },
  {
    "id": "professional-services-drill",
    "categoryGroup": "professional-services",
    "label": "Drill",
    "path": "/library/professional-services/drill.svg"
  },
  {
    "id": "professional-services-factory",
    "categoryGroup": "professional-services",
    "label": "Factory",
    "path": "/library/professional-services/factory.svg"
  },
  {
    "id": "professional-services-file-text",
    "categoryGroup": "professional-services",
    "label": "File Text",
    "path": "/library/professional-services/file-text.svg"
  },
  {
    "id": "professional-services-files",
    "categoryGroup": "professional-services",
    "label": "Files",
    "path": "/library/professional-services/files.svg"
  },
  {
    "id": "professional-services-folder",
    "categoryGroup": "professional-services",
    "label": "Folder",
    "path": "/library/professional-services/folder.svg"
  },
  {
    "id": "professional-services-folders",
    "categoryGroup": "professional-services",
    "label": "Folders",
    "path": "/library/professional-services/folders.svg"
  },
  {
    "id": "professional-services-handshake",
    "categoryGroup": "professional-services",
    "label": "Handshake",
    "path": "/library/professional-services/handshake.svg"
  },
  {
    "id": "professional-services-headset",
    "categoryGroup": "professional-services",
    "label": "Headset",
    "path": "/library/professional-services/headset.svg"
  },
  {
    "id": "professional-services-id-card",
    "categoryGroup": "professional-services",
    "label": "ID Card",
    "path": "/library/professional-services/id-card.svg"
  },
  {
    "id": "professional-services-image",
    "categoryGroup": "professional-services",
    "label": "Image",
    "path": "/library/professional-services/image.svg"
  },
  {
    "id": "professional-services-images",
    "categoryGroup": "professional-services",
    "label": "Images",
    "path": "/library/professional-services/images.svg"
  },
  {
    "id": "professional-services-inbox",
    "categoryGroup": "professional-services",
    "label": "Inbox",
    "path": "/library/professional-services/inbox.svg"
  },
  {
    "id": "professional-services-landmark",
    "categoryGroup": "professional-services",
    "label": "Landmark",
    "path": "/library/professional-services/landmark.svg"
  },
  {
    "id": "professional-services-life-buoy",
    "categoryGroup": "professional-services",
    "label": "Life Buoy",
    "path": "/library/professional-services/life-buoy.svg"
  },
  {
    "id": "professional-services-mail",
    "categoryGroup": "professional-services",
    "label": "Mail",
    "path": "/library/professional-services/mail.svg"
  },
  {
    "id": "professional-services-mic",
    "categoryGroup": "professional-services",
    "label": "Mic",
    "path": "/library/professional-services/mic.svg"
  },
  {
    "id": "professional-services-mic-2",
    "categoryGroup": "professional-services",
    "label": "Mic 2",
    "path": "/library/professional-services/mic-2.svg"
  },
  {
    "id": "professional-services-notebook",
    "categoryGroup": "professional-services",
    "label": "Notebook",
    "path": "/library/professional-services/notebook.svg"
  },
  {
    "id": "professional-services-paint-roller",
    "categoryGroup": "professional-services",
    "label": "Paint Roller",
    "path": "/library/professional-services/paint-roller.svg"
  },
  {
    "id": "professional-services-pen-tool",
    "categoryGroup": "professional-services",
    "label": "Pen Tool",
    "path": "/library/professional-services/pen-tool.svg"
  },
  {
    "id": "professional-services-phone",
    "categoryGroup": "professional-services",
    "label": "Phone",
    "path": "/library/professional-services/phone.svg"
  },
  {
    "id": "professional-services-phone-call",
    "categoryGroup": "professional-services",
    "label": "Phone Call",
    "path": "/library/professional-services/phone-call.svg"
  },
  {
    "id": "professional-services-scan",
    "categoryGroup": "professional-services",
    "label": "Scan",
    "path": "/library/professional-services/scan.svg"
  },
  {
    "id": "professional-services-sticky-note",
    "categoryGroup": "professional-services",
    "label": "Sticky Note",
    "path": "/library/professional-services/sticky-note.svg"
  },
  {
    "id": "professional-services-video",
    "categoryGroup": "professional-services",
    "label": "Video",
    "path": "/library/professional-services/video.svg"
  },
  {
    "id": "professional-services-warehouse",
    "categoryGroup": "professional-services",
    "label": "Warehouse",
    "path": "/library/professional-services/warehouse.svg"
  },
  {
    "id": "education-alarm-clock-minus",
    "categoryGroup": "education",
    "label": "Alarm Clock Minus",
    "path": "/library/education/alarm-clock-minus.svg"
  },
  {
    "id": "education-antenna",
    "categoryGroup": "education",
    "label": "Antenna",
    "path": "/library/education/antenna.svg"
  },
  {
    "id": "education-atom",
    "categoryGroup": "education",
    "label": "Atom",
    "path": "/library/education/atom.svg"
  },
  {
    "id": "education-audio-waveform",
    "categoryGroup": "education",
    "label": "Audio Waveform",
    "path": "/library/education/audio-waveform.svg"
  },
  {
    "id": "education-badge-pound-sterling",
    "categoryGroup": "education",
    "label": "Badge Pound Sterling",
    "path": "/library/education/badge-pound-sterling.svg"
  },
  {
    "id": "education-bar-chart-horizontal",
    "categoryGroup": "education",
    "label": "Bar Chart Horizontal",
    "path": "/library/education/bar-chart-horizontal.svg"
  },
  {
    "id": "education-beer-off",
    "categoryGroup": "education",
    "label": "Beer Off",
    "path": "/library/education/beer-off.svg"
  },
  {
    "id": "education-blinds",
    "categoryGroup": "education",
    "label": "Blinds",
    "path": "/library/education/blinds.svg"
  },
  {
    "id": "education-book-copy",
    "categoryGroup": "education",
    "label": "Book Copy",
    "path": "/library/education/book-copy.svg"
  },
  {
    "id": "education-book-dashed",
    "categoryGroup": "education",
    "label": "Book Dashed",
    "path": "/library/education/book-dashed.svg"
  },
  {
    "id": "education-book-marked",
    "categoryGroup": "education",
    "label": "Book Marked",
    "path": "/library/education/book-marked.svg"
  },
  {
    "id": "education-book-type",
    "categoryGroup": "education",
    "label": "Book Type",
    "path": "/library/education/book-type.svg"
  },
  {
    "id": "education-bottle-wine",
    "categoryGroup": "education",
    "label": "Bottle Wine",
    "path": "/library/education/bottle-wine.svg"
  },
  {
    "id": "education-broom-sparkles",
    "categoryGroup": "education",
    "label": "Broom Sparkles",
    "path": "/library/education/broom-sparkles.svg"
  },
  {
    "id": "education-calculator",
    "categoryGroup": "education",
    "label": "Calculator",
    "path": "/library/education/calculator.svg"
  },
  {
    "id": "education-drum",
    "categoryGroup": "education",
    "label": "Drum",
    "path": "/library/education/drum.svg"
  },
  {
    "id": "education-earth",
    "categoryGroup": "education",
    "label": "Earth",
    "path": "/library/education/earth.svg"
  },
  {
    "id": "education-globe",
    "categoryGroup": "education",
    "label": "Globe",
    "path": "/library/education/globe.svg"
  },
  {
    "id": "education-globe-2",
    "categoryGroup": "education",
    "label": "Globe 2",
    "path": "/library/education/globe-2.svg"
  },
  {
    "id": "education-graduation-cap",
    "categoryGroup": "education",
    "label": "Graduation Cap",
    "path": "/library/education/graduation-cap.svg",
    "categorySlug": "tuition-center"
  },
  {
    "id": "education-guitar",
    "categoryGroup": "education",
    "label": "Guitar",
    "path": "/library/education/guitar.svg",
    "categorySlug": "music-school"
  },
  {
    "id": "education-languages",
    "categoryGroup": "education",
    "label": "Languages",
    "path": "/library/education/languages.svg",
    "categorySlug": "language-institute"
  },
  {
    "id": "education-lightbulb",
    "categoryGroup": "education",
    "label": "Lightbulb",
    "path": "/library/education/lightbulb.svg"
  },
  {
    "id": "education-lightbulb-off",
    "categoryGroup": "education",
    "label": "Lightbulb Off",
    "path": "/library/education/lightbulb-off.svg"
  },
  {
    "id": "education-microscope",
    "categoryGroup": "education",
    "label": "Microscope",
    "path": "/library/education/microscope.svg"
  },
  {
    "id": "education-monitor-play",
    "categoryGroup": "education",
    "label": "Monitor Play",
    "path": "/library/education/monitor-play.svg"
  },
  {
    "id": "education-music",
    "categoryGroup": "education",
    "label": "Music",
    "path": "/library/education/music.svg",
    "categorySlug": "music-school"
  },
  {
    "id": "education-music-2",
    "categoryGroup": "education",
    "label": "Music 2",
    "path": "/library/education/music-2.svg",
    "categorySlug": "music-school"
  },
  {
    "id": "education-music-3",
    "categoryGroup": "education",
    "label": "Music 3",
    "path": "/library/education/music-3.svg"
  },
  {
    "id": "education-music-4",
    "categoryGroup": "education",
    "label": "Music 4",
    "path": "/library/education/music-4.svg"
  },
  {
    "id": "education-notebook-pen",
    "categoryGroup": "education",
    "label": "Notebook Pen",
    "path": "/library/education/notebook-pen.svg"
  },
  {
    "id": "education-notebook-tabs",
    "categoryGroup": "education",
    "label": "Notebook Tabs",
    "path": "/library/education/notebook-tabs.svg"
  },
  {
    "id": "education-pen-line",
    "categoryGroup": "education",
    "label": "Pen Line",
    "path": "/library/education/pen-line.svg"
  },
  {
    "id": "education-piano",
    "categoryGroup": "education",
    "label": "Piano",
    "path": "/library/education/piano.svg",
    "categorySlug": "music-school"
  },
  {
    "id": "education-presentation",
    "categoryGroup": "education",
    "label": "Presentation",
    "path": "/library/education/presentation.svg"
  },
  {
    "id": "education-projector",
    "categoryGroup": "education",
    "label": "Projector",
    "path": "/library/education/projector.svg"
  },
  {
    "id": "education-radio",
    "categoryGroup": "education",
    "label": "Radio",
    "path": "/library/education/radio.svg"
  },
  {
    "id": "education-school",
    "categoryGroup": "education",
    "label": "School",
    "path": "/library/education/school.svg",
    "categorySlug": "tuition-center"
  },
  {
    "id": "education-telescope",
    "categoryGroup": "education",
    "label": "Telescope",
    "path": "/library/education/telescope.svg"
  },
  {
    "id": "education-tv",
    "categoryGroup": "education",
    "label": "TV",
    "path": "/library/education/tv.svg"
  },
  {
    "id": "education-university",
    "categoryGroup": "education",
    "label": "University",
    "path": "/library/education/university.svg"
  },
  {
    "id": "pet-services-alarm-clock-off",
    "categoryGroup": "pet-services",
    "label": "Alarm Clock Off",
    "path": "/library/pet-services/alarm-clock-off.svg"
  },
  {
    "id": "pet-services-ambulance",
    "categoryGroup": "pet-services",
    "label": "Ambulance",
    "path": "/library/pet-services/ambulance.svg"
  },
  {
    "id": "pet-services-app-window",
    "categoryGroup": "pet-services",
    "label": "App Window",
    "path": "/library/pet-services/app-window.svg"
  },
  {
    "id": "pet-services-axe",
    "categoryGroup": "pet-services",
    "label": "Axe",
    "path": "/library/pet-services/axe.svg"
  },
  {
    "id": "pet-services-badge-plus",
    "categoryGroup": "pet-services",
    "label": "Badge Plus",
    "path": "/library/pet-services/badge-plus.svg"
  },
  {
    "id": "pet-services-badge-question-mark",
    "categoryGroup": "pet-services",
    "label": "Badge Question Mark",
    "path": "/library/pet-services/badge-question-mark.svg"
  },
  {
    "id": "pet-services-bar-chart-horizontal-big",
    "categoryGroup": "pet-services",
    "label": "Bar Chart Horizontal Big",
    "path": "/library/pet-services/bar-chart-horizontal-big.svg"
  },
  {
    "id": "pet-services-bell-check",
    "categoryGroup": "pet-services",
    "label": "Bell Check",
    "path": "/library/pet-services/bell-check.svg"
  },
  {
    "id": "pet-services-bird",
    "categoryGroup": "pet-services",
    "label": "Bird",
    "path": "/library/pet-services/bird.svg"
  },
  {
    "id": "pet-services-blocks",
    "categoryGroup": "pet-services",
    "label": "Blocks",
    "path": "/library/pet-services/blocks.svg"
  },
  {
    "id": "pet-services-book-down",
    "categoryGroup": "pet-services",
    "label": "Book Down",
    "path": "/library/pet-services/book-down.svg"
  },
  {
    "id": "pet-services-book-up",
    "categoryGroup": "pet-services",
    "label": "Book UP",
    "path": "/library/pet-services/book-up.svg"
  },
  {
    "id": "pet-services-bow-arrow",
    "categoryGroup": "pet-services",
    "label": "Bow Arrow",
    "path": "/library/pet-services/bow-arrow.svg"
  },
  {
    "id": "pet-services-brush-cleaning",
    "categoryGroup": "pet-services",
    "label": "Brush Cleaning",
    "path": "/library/pet-services/brush-cleaning.svg"
  },
  {
    "id": "pet-services-bug",
    "categoryGroup": "pet-services",
    "label": "Bug",
    "path": "/library/pet-services/bug.svg"
  },
  {
    "id": "pet-services-cat",
    "categoryGroup": "pet-services",
    "label": "Cat",
    "path": "/library/pet-services/cat.svg",
    "categorySlug": "pet-shop"
  },
  {
    "id": "pet-services-dog",
    "categoryGroup": "pet-services",
    "label": "Dog",
    "path": "/library/pet-services/dog.svg",
    "categorySlug": "pet-shop"
  },
  {
    "id": "pet-services-home",
    "categoryGroup": "pet-services",
    "label": "Home",
    "path": "/library/pet-services/home.svg",
    "categorySlug": "cleaning-service"
  },
  {
    "id": "pet-services-house",
    "categoryGroup": "pet-services",
    "label": "House",
    "path": "/library/pet-services/house.svg",
    "categorySlug": "cleaning-service"
  },
  {
    "id": "pet-services-paw-print",
    "categoryGroup": "pet-services",
    "label": "Paw Print",
    "path": "/library/pet-services/paw-print.svg",
    "categorySlug": "pet-grooming"
  },
  {
    "id": "pet-services-pill",
    "categoryGroup": "pet-services",
    "label": "Pill",
    "path": "/library/pet-services/pill.svg",
    "categorySlug": "pharmacy"
  },
  {
    "id": "pet-services-rabbit",
    "categoryGroup": "pet-services",
    "label": "Rabbit",
    "path": "/library/pet-services/rabbit.svg"
  },
  {
    "id": "pet-services-shield-plus",
    "categoryGroup": "pet-services",
    "label": "Shield Plus",
    "path": "/library/pet-services/shield-plus.svg"
  },
  {
    "id": "pet-services-snail",
    "categoryGroup": "pet-services",
    "label": "Snail",
    "path": "/library/pet-services/snail.svg"
  },
  {
    "id": "pet-services-squirrel",
    "categoryGroup": "pet-services",
    "label": "Squirrel",
    "path": "/library/pet-services/squirrel.svg"
  },
  {
    "id": "pet-services-stethoscope",
    "categoryGroup": "pet-services",
    "label": "Stethoscope",
    "path": "/library/pet-services/stethoscope.svg",
    "categorySlug": "veterinary-service"
  },
  {
    "id": "pet-services-syringe",
    "categoryGroup": "pet-services",
    "label": "Syringe",
    "path": "/library/pet-services/syringe.svg"
  },
  {
    "id": "pet-services-turtle",
    "categoryGroup": "pet-services",
    "label": "Turtle",
    "path": "/library/pet-services/turtle.svg"
  },
  {
    "id": "pet-services-worm",
    "categoryGroup": "pet-services",
    "label": "Worm",
    "path": "/library/pet-services/worm.svg"
  },
  {
    "id": "home-services-air-vent",
    "categoryGroup": "home-services",
    "label": "Air Vent",
    "path": "/library/home-services/air-vent.svg"
  },
  {
    "id": "home-services-alarm-clock-plus",
    "categoryGroup": "home-services",
    "label": "Alarm Clock Plus",
    "path": "/library/home-services/alarm-clock-plus.svg"
  },
  {
    "id": "home-services-app-window-mac",
    "categoryGroup": "home-services",
    "label": "App Window Mac",
    "path": "/library/home-services/app-window-mac.svg"
  },
  {
    "id": "home-services-axis-3-d",
    "categoryGroup": "home-services",
    "label": "Axis 3 D",
    "path": "/library/home-services/axis-3-d.svg"
  },
  {
    "id": "home-services-badge-russian-ruble",
    "categoryGroup": "home-services",
    "label": "Badge Russian Ruble",
    "path": "/library/home-services/badge-russian-ruble.svg"
  },
  {
    "id": "home-services-barrel",
    "categoryGroup": "home-services",
    "label": "Barrel",
    "path": "/library/home-services/barrel.svg"
  },
  {
    "id": "home-services-bed",
    "categoryGroup": "home-services",
    "label": "Bed",
    "path": "/library/home-services/bed.svg",
    "categorySlug": "hotel"
  },
  {
    "id": "home-services-bell-dot",
    "categoryGroup": "home-services",
    "label": "Bell Dot",
    "path": "/library/home-services/bell-dot.svg"
  },
  {
    "id": "home-services-bluetooth",
    "categoryGroup": "home-services",
    "label": "Bluetooth",
    "path": "/library/home-services/bluetooth.svg"
  },
  {
    "id": "home-services-book-headphones",
    "categoryGroup": "home-services",
    "label": "Book Headphones",
    "path": "/library/home-services/book-headphones.svg"
  },
  {
    "id": "home-services-book-up-2",
    "categoryGroup": "home-services",
    "label": "Book UP 2",
    "path": "/library/home-services/book-up-2.svg"
  },
  {
    "id": "home-services-box-select",
    "categoryGroup": "home-services",
    "label": "Box Select",
    "path": "/library/home-services/box-select.svg"
  },
  {
    "id": "home-services-bubbles",
    "categoryGroup": "home-services",
    "label": "Bubbles",
    "path": "/library/home-services/bubbles.svg"
  },
  {
    "id": "home-services-cable",
    "categoryGroup": "home-services",
    "label": "Cable",
    "path": "/library/home-services/cable.svg"
  },
  {
    "id": "home-services-fan",
    "categoryGroup": "home-services",
    "label": "Fan",
    "path": "/library/home-services/fan.svg"
  },
  {
    "id": "home-services-lamp",
    "categoryGroup": "home-services",
    "label": "Lamp",
    "path": "/library/home-services/lamp.svg"
  },
  {
    "id": "home-services-lamp-desk",
    "categoryGroup": "home-services",
    "label": "Lamp Desk",
    "path": "/library/home-services/lamp-desk.svg"
  },
  {
    "id": "home-services-lamp-floor",
    "categoryGroup": "home-services",
    "label": "Lamp Floor",
    "path": "/library/home-services/lamp-floor.svg"
  },
  {
    "id": "home-services-plug",
    "categoryGroup": "home-services",
    "label": "Plug",
    "path": "/library/home-services/plug.svg"
  },
  {
    "id": "home-services-plug-zap",
    "categoryGroup": "home-services",
    "label": "Plug Zap",
    "path": "/library/home-services/plug-zap.svg"
  },
  {
    "id": "home-services-rat",
    "categoryGroup": "home-services",
    "label": "Rat",
    "path": "/library/home-services/rat.svg"
  },
  {
    "id": "home-services-recycle",
    "categoryGroup": "home-services",
    "label": "Recycle",
    "path": "/library/home-services/recycle.svg"
  },
  {
    "id": "home-services-shovel",
    "categoryGroup": "home-services",
    "label": "Shovel",
    "path": "/library/home-services/shovel.svg"
  },
  {
    "id": "home-services-sofa",
    "categoryGroup": "home-services",
    "label": "Sofa",
    "path": "/library/home-services/sofa.svg"
  },
  {
    "id": "home-services-sprout",
    "categoryGroup": "home-services",
    "label": "Sprout",
    "path": "/library/home-services/sprout.svg",
    "categorySlug": "gardening-service"
  },
  {
    "id": "home-services-trash",
    "categoryGroup": "home-services",
    "label": "Trash",
    "path": "/library/home-services/trash.svg"
  },
  {
    "id": "home-services-trash-2",
    "categoryGroup": "home-services",
    "label": "Trash 2",
    "path": "/library/home-services/trash-2.svg"
  },
  {
    "id": "home-services-tree-deciduous",
    "categoryGroup": "home-services",
    "label": "Tree Deciduous",
    "path": "/library/home-services/tree-deciduous.svg"
  },
  {
    "id": "home-services-tree-pine",
    "categoryGroup": "home-services",
    "label": "Tree Pine",
    "path": "/library/home-services/tree-pine.svg",
    "categorySlug": "gardening-service"
  },
  {
    "id": "home-services-washing-machine",
    "categoryGroup": "home-services",
    "label": "Washing Machine",
    "path": "/library/home-services/washing-machine.svg"
  },
  {
    "id": "hospitality-alarm-minus",
    "categoryGroup": "hospitality",
    "label": "Alarm Minus",
    "path": "/library/hospitality/alarm-minus.svg"
  },
  {
    "id": "hospitality-anchor",
    "categoryGroup": "hospitality",
    "label": "Anchor",
    "path": "/library/hospitality/anchor.svg"
  },
  {
    "id": "hospitality-archive-restore",
    "categoryGroup": "hospitality",
    "label": "Archive Restore",
    "path": "/library/hospitality/archive-restore.svg"
  },
  {
    "id": "hospitality-axis-3d",
    "categoryGroup": "hospitality",
    "label": "Axis 3D",
    "path": "/library/hospitality/axis-3d.svg"
  },
  {
    "id": "hospitality-badge-swiss-franc",
    "categoryGroup": "hospitality",
    "label": "Badge Swiss Franc",
    "path": "/library/hospitality/badge-swiss-franc.svg"
  },
  {
    "id": "hospitality-baggage-claim",
    "categoryGroup": "hospitality",
    "label": "Baggage Claim",
    "path": "/library/hospitality/baggage-claim.svg"
  },
  {
    "id": "hospitality-baseline",
    "categoryGroup": "hospitality",
    "label": "Baseline",
    "path": "/library/hospitality/baseline.svg"
  },
  {
    "id": "hospitality-bed-double",
    "categoryGroup": "hospitality",
    "label": "Bed Double",
    "path": "/library/hospitality/bed-double.svg",
    "categorySlug": "hotel"
  },
  {
    "id": "hospitality-bed-single",
    "categoryGroup": "hospitality",
    "label": "Bed Single",
    "path": "/library/hospitality/bed-single.svg"
  },
  {
    "id": "hospitality-bell-electric",
    "categoryGroup": "hospitality",
    "label": "Bell Electric",
    "path": "/library/hospitality/bell-electric.svg"
  },
  {
    "id": "hospitality-bluetooth-connected",
    "categoryGroup": "hospitality",
    "label": "Bluetooth Connected",
    "path": "/library/hospitality/bluetooth-connected.svg"
  },
  {
    "id": "hospitality-book-heart",
    "categoryGroup": "hospitality",
    "label": "Book Heart",
    "path": "/library/hospitality/book-heart.svg"
  },
  {
    "id": "hospitality-book-user",
    "categoryGroup": "hospitality",
    "label": "Book User",
    "path": "/library/hospitality/book-user.svg"
  },
  {
    "id": "hospitality-braces",
    "categoryGroup": "hospitality",
    "label": "Braces",
    "path": "/library/hospitality/braces.svg"
  },
  {
    "id": "hospitality-bug-off",
    "categoryGroup": "hospitality",
    "label": "Bug Off",
    "path": "/library/hospitality/bug-off.svg"
  },
  {
    "id": "hospitality-calendar",
    "categoryGroup": "hospitality",
    "label": "Calendar",
    "path": "/library/hospitality/calendar.svg"
  },
  {
    "id": "hospitality-concierge-bell",
    "categoryGroup": "hospitality",
    "label": "Concierge Bell",
    "path": "/library/hospitality/concierge-bell.svg"
  },
  {
    "id": "hospitality-hotel",
    "categoryGroup": "hospitality",
    "label": "Hotel",
    "path": "/library/hospitality/hotel.svg",
    "categorySlug": "hotel"
  },
  {
    "id": "hospitality-luggage",
    "categoryGroup": "hospitality",
    "label": "Luggage",
    "path": "/library/hospitality/luggage.svg",
    "categorySlug": "travel-agency"
  },
  {
    "id": "hospitality-palmtree",
    "categoryGroup": "hospitality",
    "label": "Palmtree",
    "path": "/library/hospitality/palmtree.svg"
  },
  {
    "id": "hospitality-plane",
    "categoryGroup": "hospitality",
    "label": "Plane",
    "path": "/library/hospitality/plane.svg",
    "categorySlug": "travel-agency"
  },
  {
    "id": "hospitality-plane-landing",
    "categoryGroup": "hospitality",
    "label": "Plane Landing",
    "path": "/library/hospitality/plane-landing.svg"
  },
  {
    "id": "hospitality-plane-takeoff",
    "categoryGroup": "hospitality",
    "label": "Plane Takeoff",
    "path": "/library/hospitality/plane-takeoff.svg"
  },
  {
    "id": "hospitality-sailboat",
    "categoryGroup": "hospitality",
    "label": "Sailboat",
    "path": "/library/hospitality/sailboat.svg"
  },
  {
    "id": "hospitality-ship",
    "categoryGroup": "hospitality",
    "label": "Ship",
    "path": "/library/hospitality/ship.svg"
  },
  {
    "id": "hospitality-train-front",
    "categoryGroup": "hospitality",
    "label": "Train Front",
    "path": "/library/hospitality/train-front.svg"
  },
  {
    "id": "hospitality-umbrella",
    "categoryGroup": "hospitality",
    "label": "Umbrella",
    "path": "/library/hospitality/umbrella.svg"
  },
  {
    "id": "event-services-alarm-plus",
    "categoryGroup": "event-services",
    "label": "Alarm Plus",
    "path": "/library/event-services/alarm-plus.svg"
  },
  {
    "id": "event-services-archive-x",
    "categoryGroup": "event-services",
    "label": "Archive X",
    "path": "/library/event-services/archive-x.svg"
  },
  {
    "id": "event-services-baby",
    "categoryGroup": "event-services",
    "label": "Baby",
    "path": "/library/event-services/baby.svg"
  },
  {
    "id": "event-services-badge-turkish-lira",
    "categoryGroup": "event-services",
    "label": "Badge Turkish Lira",
    "path": "/library/event-services/badge-turkish-lira.svg"
  },
  {
    "id": "event-services-balloon",
    "categoryGroup": "event-services",
    "label": "Balloon",
    "path": "/library/event-services/balloon.svg",
    "categorySlug": "decoration-service"
  },
  {
    "id": "event-services-battery",
    "categoryGroup": "event-services",
    "label": "Battery",
    "path": "/library/event-services/battery.svg"
  },
  {
    "id": "event-services-bell-minus",
    "categoryGroup": "event-services",
    "label": "Bell Minus",
    "path": "/library/event-services/bell-minus.svg"
  },
  {
    "id": "event-services-bluetooth-off",
    "categoryGroup": "event-services",
    "label": "Bluetooth Off",
    "path": "/library/event-services/bluetooth-off.svg"
  },
  {
    "id": "event-services-book-image",
    "categoryGroup": "event-services",
    "label": "Book Image",
    "path": "/library/event-services/book-image.svg"
  },
  {
    "id": "event-services-book-x",
    "categoryGroup": "event-services",
    "label": "Book X",
    "path": "/library/event-services/book-x.svg"
  },
  {
    "id": "event-services-brain-circuit",
    "categoryGroup": "event-services",
    "label": "Brain Circuit",
    "path": "/library/event-services/brain-circuit.svg"
  },
  {
    "id": "event-services-bug-play",
    "categoryGroup": "event-services",
    "label": "Bug Play",
    "path": "/library/event-services/bug-play.svg"
  },
  {
    "id": "event-services-calendar-check",
    "categoryGroup": "event-services",
    "label": "Calendar Check",
    "path": "/library/event-services/calendar-check.svg"
  },
  {
    "id": "event-services-calendar-heart",
    "categoryGroup": "event-services",
    "label": "Calendar Heart",
    "path": "/library/event-services/calendar-heart.svg",
    "categorySlug": "wedding-studio"
  },
  {
    "id": "event-services-church",
    "categoryGroup": "event-services",
    "label": "Church",
    "path": "/library/event-services/church.svg"
  },
  {
    "id": "event-services-ferris-wheel",
    "categoryGroup": "event-services",
    "label": "Ferris Wheel",
    "path": "/library/event-services/ferris-wheel.svg"
  },
  {
    "id": "event-services-party-popper",
    "categoryGroup": "event-services",
    "label": "Party Popper",
    "path": "/library/event-services/party-popper.svg",
    "categorySlug": "event-planner"
  },
  {
    "id": "event-services-tent",
    "categoryGroup": "event-services",
    "label": "Tent",
    "path": "/library/event-services/tent.svg"
  },
  {
    "id": "event-services-user-plus",
    "categoryGroup": "event-services",
    "label": "User Plus",
    "path": "/library/event-services/user-plus.svg"
  },
  {
    "id": "healthcare-alarm-smoke",
    "categoryGroup": "healthcare",
    "label": "Alarm Smoke",
    "path": "/library/healthcare/alarm-smoke.svg"
  },
  {
    "id": "healthcare-area-chart",
    "categoryGroup": "healthcare",
    "label": "Area Chart",
    "path": "/library/healthcare/area-chart.svg"
  },
  {
    "id": "healthcare-badge",
    "categoryGroup": "healthcare",
    "label": "Badge",
    "path": "/library/healthcare/badge.svg"
  },
  {
    "id": "healthcare-badge-x",
    "categoryGroup": "healthcare",
    "label": "Badge X",
    "path": "/library/healthcare/badge-x.svg"
  },
  {
    "id": "healthcare-bandage",
    "categoryGroup": "healthcare",
    "label": "Bandage",
    "path": "/library/healthcare/bandage.svg"
  },
  {
    "id": "healthcare-battery-charging",
    "categoryGroup": "healthcare",
    "label": "Battery Charging",
    "path": "/library/healthcare/battery-charging.svg"
  },
  {
    "id": "healthcare-bell-off",
    "categoryGroup": "healthcare",
    "label": "Bell Off",
    "path": "/library/healthcare/bell-off.svg"
  },
  {
    "id": "healthcare-bluetooth-searching",
    "categoryGroup": "healthcare",
    "label": "Bluetooth Searching",
    "path": "/library/healthcare/bluetooth-searching.svg"
  },
  {
    "id": "healthcare-book-key",
    "categoryGroup": "healthcare",
    "label": "Book Key",
    "path": "/library/healthcare/book-key.svg"
  },
  {
    "id": "healthcare-bookmark",
    "categoryGroup": "healthcare",
    "label": "Bookmark",
    "path": "/library/healthcare/bookmark.svg"
  },
  {
    "id": "healthcare-brain-cog",
    "categoryGroup": "healthcare",
    "label": "Brain Cog",
    "path": "/library/healthcare/brain-cog.svg"
  },
  {
    "id": "healthcare-cable-car",
    "categoryGroup": "healthcare",
    "label": "Cable Car",
    "path": "/library/healthcare/cable-car.svg"
  },
  {
    "id": "healthcare-clipboard-plus",
    "categoryGroup": "healthcare",
    "label": "Clipboard Plus",
    "path": "/library/healthcare/clipboard-plus.svg"
  },
  {
    "id": "healthcare-cross",
    "categoryGroup": "healthcare",
    "label": "Cross",
    "path": "/library/healthcare/cross.svg"
  },
  {
    "id": "healthcare-dna",
    "categoryGroup": "healthcare",
    "label": "Dna",
    "path": "/library/healthcare/dna.svg"
  },
  {
    "id": "healthcare-ear",
    "categoryGroup": "healthcare",
    "label": "Ear",
    "path": "/library/healthcare/ear.svg"
  },
  {
    "id": "healthcare-ear-off",
    "categoryGroup": "healthcare",
    "label": "Ear Off",
    "path": "/library/healthcare/ear-off.svg"
  },
  {
    "id": "healthcare-file-heart",
    "categoryGroup": "healthcare",
    "label": "File Heart",
    "path": "/library/healthcare/file-heart.svg"
  },
  {
    "id": "healthcare-hospital",
    "categoryGroup": "healthcare",
    "label": "Hospital",
    "path": "/library/healthcare/hospital.svg",
    "categorySlug": "dental-clinic"
  },
  {
    "id": "healthcare-pill-bottle",
    "categoryGroup": "healthcare",
    "label": "Pill Bottle",
    "path": "/library/healthcare/pill-bottle.svg",
    "categorySlug": "pharmacy"
  },
  {
    "id": "healthcare-plus",
    "categoryGroup": "healthcare",
    "label": "Plus",
    "path": "/library/healthcare/plus.svg"
  },
  {
    "id": "healthcare-tablets",
    "categoryGroup": "healthcare",
    "label": "Tablets",
    "path": "/library/healthcare/tablets.svg",
    "categorySlug": "pharmacy"
  },
  {
    "id": "entertainment-album",
    "categoryGroup": "entertainment",
    "label": "Album",
    "path": "/library/entertainment/album.svg"
  },
  {
    "id": "entertainment-armchair",
    "categoryGroup": "entertainment",
    "label": "Armchair",
    "path": "/library/entertainment/armchair.svg"
  },
  {
    "id": "entertainment-badge-alert",
    "categoryGroup": "entertainment",
    "label": "Badge Alert",
    "path": "/library/entertainment/badge-alert.svg"
  },
  {
    "id": "entertainment-ban",
    "categoryGroup": "entertainment",
    "label": "Ban",
    "path": "/library/entertainment/ban.svg"
  },
  {
    "id": "entertainment-battery-full",
    "categoryGroup": "entertainment",
    "label": "Battery Full",
    "path": "/library/entertainment/battery-full.svg"
  },
  {
    "id": "entertainment-bell-plus",
    "categoryGroup": "entertainment",
    "label": "Bell Plus",
    "path": "/library/entertainment/bell-plus.svg"
  },
  {
    "id": "entertainment-bold",
    "categoryGroup": "entertainment",
    "label": "Bold",
    "path": "/library/entertainment/bold.svg"
  },
  {
    "id": "entertainment-book-lock",
    "categoryGroup": "entertainment",
    "label": "Book Lock",
    "path": "/library/entertainment/book-lock.svg"
  },
  {
    "id": "entertainment-bookmark-check",
    "categoryGroup": "entertainment",
    "label": "Bookmark Check",
    "path": "/library/entertainment/bookmark-check.svg"
  },
  {
    "id": "entertainment-bot",
    "categoryGroup": "entertainment",
    "label": "Bot",
    "path": "/library/entertainment/bot.svg"
  },
  {
    "id": "entertainment-brick-wall",
    "categoryGroup": "entertainment",
    "label": "Brick Wall",
    "path": "/library/entertainment/brick-wall.svg"
  },
  {
    "id": "entertainment-calendar-1",
    "categoryGroup": "entertainment",
    "label": "Calendar 1",
    "path": "/library/entertainment/calendar-1.svg"
  },
  {
    "id": "entertainment-dice-1",
    "categoryGroup": "entertainment",
    "label": "Dice 1",
    "path": "/library/entertainment/dice-1.svg"
  },
  {
    "id": "entertainment-dice-2",
    "categoryGroup": "entertainment",
    "label": "Dice 2",
    "path": "/library/entertainment/dice-2.svg"
  },
  {
    "id": "entertainment-dice-3",
    "categoryGroup": "entertainment",
    "label": "Dice 3",
    "path": "/library/entertainment/dice-3.svg"
  },
  {
    "id": "entertainment-dice-4",
    "categoryGroup": "entertainment",
    "label": "Dice 4",
    "path": "/library/entertainment/dice-4.svg"
  },
  {
    "id": "entertainment-dice-5",
    "categoryGroup": "entertainment",
    "label": "Dice 5",
    "path": "/library/entertainment/dice-5.svg"
  },
  {
    "id": "entertainment-dice-6",
    "categoryGroup": "entertainment",
    "label": "Dice 6",
    "path": "/library/entertainment/dice-6.svg"
  },
  {
    "id": "entertainment-drama",
    "categoryGroup": "entertainment",
    "label": "Drama",
    "path": "/library/entertainment/drama.svg"
  },
  {
    "id": "entertainment-film",
    "categoryGroup": "entertainment",
    "label": "Film",
    "path": "/library/entertainment/film.svg",
    "categorySlug": "cinema"
  },
  {
    "id": "entertainment-gamepad",
    "categoryGroup": "entertainment",
    "label": "Gamepad",
    "path": "/library/entertainment/gamepad.svg",
    "categorySlug": "gaming-center"
  },
  {
    "id": "entertainment-gamepad-2",
    "categoryGroup": "entertainment",
    "label": "Gamepad 2",
    "path": "/library/entertainment/gamepad-2.svg",
    "categorySlug": "gaming-center"
  },
  {
    "id": "entertainment-ghost",
    "categoryGroup": "entertainment",
    "label": "Ghost",
    "path": "/library/entertainment/ghost.svg"
  },
  {
    "id": "entertainment-joystick",
    "categoryGroup": "entertainment",
    "label": "Joystick",
    "path": "/library/entertainment/joystick.svg"
  },
  {
    "id": "entertainment-roller-coaster",
    "categoryGroup": "entertainment",
    "label": "Roller Coaster",
    "path": "/library/entertainment/roller-coaster.svg"
  },
  {
    "id": "entertainment-shield",
    "categoryGroup": "entertainment",
    "label": "Shield",
    "path": "/library/entertainment/shield.svg"
  },
  {
    "id": "entertainment-swords",
    "categoryGroup": "entertainment",
    "label": "Swords",
    "path": "/library/entertainment/swords.svg"
  },
  {
    "id": "entertainment-volume-2",
    "categoryGroup": "entertainment",
    "label": "Volume 2",
    "path": "/library/entertainment/volume-2.svg"
  },
  {
    "id": "ecommerce-alert-circle",
    "categoryGroup": "ecommerce",
    "label": "Alert Circle",
    "path": "/library/ecommerce/alert-circle.svg"
  },
  {
    "id": "ecommerce-archive",
    "categoryGroup": "ecommerce",
    "label": "Archive",
    "path": "/library/ecommerce/archive.svg"
  },
  {
    "id": "ecommerce-arrows-up-from-line",
    "categoryGroup": "ecommerce",
    "label": "Arrows UP From Line",
    "path": "/library/ecommerce/arrows-up-from-line.svg"
  },
  {
    "id": "ecommerce-badge-cent",
    "categoryGroup": "ecommerce",
    "label": "Badge Cent",
    "path": "/library/ecommerce/badge-cent.svg"
  },
  {
    "id": "ecommerce-banknote-check",
    "categoryGroup": "ecommerce",
    "label": "Banknote Check",
    "path": "/library/ecommerce/banknote-check.svg"
  },
  {
    "id": "ecommerce-battery-low",
    "categoryGroup": "ecommerce",
    "label": "Battery Low",
    "path": "/library/ecommerce/battery-low.svg"
  },
  {
    "id": "ecommerce-bell",
    "categoryGroup": "ecommerce",
    "label": "Bell",
    "path": "/library/ecommerce/bell.svg"
  },
  {
    "id": "ecommerce-bell-ring",
    "categoryGroup": "ecommerce",
    "label": "Bell Ring",
    "path": "/library/ecommerce/bell-ring.svg"
  },
  {
    "id": "ecommerce-bolt",
    "categoryGroup": "ecommerce",
    "label": "Bolt",
    "path": "/library/ecommerce/bolt.svg"
  },
  {
    "id": "ecommerce-book-minus",
    "categoryGroup": "ecommerce",
    "label": "Book Minus",
    "path": "/library/ecommerce/book-minus.svg"
  },
  {
    "id": "ecommerce-bookmark-minus",
    "categoryGroup": "ecommerce",
    "label": "Bookmark Minus",
    "path": "/library/ecommerce/bookmark-minus.svg"
  },
  {
    "id": "ecommerce-box",
    "categoryGroup": "ecommerce",
    "label": "Box",
    "path": "/library/ecommerce/box.svg"
  },
  {
    "id": "ecommerce-boxes",
    "categoryGroup": "ecommerce",
    "label": "Boxes",
    "path": "/library/ecommerce/boxes.svg"
  },
  {
    "id": "ecommerce-brick-wall-fire",
    "categoryGroup": "ecommerce",
    "label": "Brick Wall Fire",
    "path": "/library/ecommerce/brick-wall-fire.svg"
  },
  {
    "id": "ecommerce-calendar-check-2",
    "categoryGroup": "ecommerce",
    "label": "Calendar Check 2",
    "path": "/library/ecommerce/calendar-check-2.svg"
  },
  {
    "id": "ecommerce-external-link",
    "categoryGroup": "ecommerce",
    "label": "External Link",
    "path": "/library/ecommerce/external-link.svg"
  },
  {
    "id": "ecommerce-link",
    "categoryGroup": "ecommerce",
    "label": "Link",
    "path": "/library/ecommerce/link.svg"
  },
  {
    "id": "ecommerce-megaphone",
    "categoryGroup": "ecommerce",
    "label": "Megaphone",
    "path": "/library/ecommerce/megaphone.svg"
  },
  {
    "id": "ecommerce-rss",
    "categoryGroup": "ecommerce",
    "label": "Rss",
    "path": "/library/ecommerce/rss.svg"
  },
  {
    "id": "ecommerce-send",
    "categoryGroup": "ecommerce",
    "label": "Send",
    "path": "/library/ecommerce/send.svg"
  },
  {
    "id": "ecommerce-share-2",
    "categoryGroup": "ecommerce",
    "label": "Share 2",
    "path": "/library/ecommerce/share-2.svg"
  },
  {
    "id": "ecommerce-thumbs-up",
    "categoryGroup": "ecommerce",
    "label": "Thumbs UP",
    "path": "/library/ecommerce/thumbs-up.svg"
  }
];
